spring.application.name=bankapi

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante criação correta da estrutura
spring.jpa.defer-datasource-initialization=true

# Corrige possíveis problemas de nomes reservados SQL
spring.jpa.properties.hibernate.globally_quoted_identifiers=true